baseURL = "https://maolonglong.github.io"
languageCode = "zh-CN"
title = "æ¯›ç‘ç‘çš„åšå®¢"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## ä¿æŒåˆ†ç±»çš„åŸå§‹åå­—ï¼ˆfalseä¼šåšè½¬å°å†™å¤„ç†ï¼‰
preserveTaxonomyNames = true
## æ˜¯å¦ç¦æ­¢URL Pathè½¬å°å†™
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140

disqusShortname = ""  ## æ˜¯å¦å¼€å¯disqusè¯„è®ºï¼Œä¸è¦å’ŒutterancåŒæ—¶å¼€å¯

[author]
  name = "æ¯›ç‘ç‘"

[params]
  author = "æ¯›ç‘ç‘"
  subtitle = "åªæœ‰éå¸¸åŠªåŠ›ï¼Œæ‰èƒ½æ˜¾å¾—æ¯«ä¸è´¹åŠ›"
  keywords = ""
  description = ""
  busuanzi = false #å¯ç”¨ä¸ç®—å­ç½‘é¡µç»Ÿè®¡
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # å¯ç”¨æœ¬åœ°æœç´¢

  # è¿™é‡Œæˆ‘å­˜æ”¾åœ¨äº†ä¸»é¢˜çš„staticæ–‡ä»¶å¤¹é‡Œï¼Œæ ¹ç›®å½•çš„ä¼¼ä¹ä¹Ÿå¯ä»¥
  customCSS = []
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []
  # if ['custom.js'], load '/static/js/custom.js' file

  # å…¨å±€å¼€å…³ï¼Œä½ ä¹Ÿå¯ä»¥åœ¨æ¯ä¸€ç¯‡å†…å®¹çš„ front matter ä¸­é’ˆå¯¹å•ç¯‡å†…å®¹å…³é—­æˆ–å¼€å¯æŸäº›åŠŸèƒ½
  toc = false  # æ˜¯å¦å¼€å¯ç›®å½•

  # å¤‡æ¡ˆå·
  beian = ""

  # å›¾ç‰‡æ”¾å¤§
  fancybox = true

[params.image_cdn]
    enable = true
    Host = "https://cdn.jsdelivr.net/gh/MaoLongLong/maolonglong.github.io@gh-pages"

## å‹æƒ…é“¾æ¥ï¼Œå¯ä»¥å¤šä¸ª

# [[params.links]]
#   title = "é£é›ªæ— æƒ…çš„åšå®¢"
#   name = "é£é›ªæ— æƒ…çš„åšå®¢"
#   url = "https://www.flysnow.org/"

# [[params.links]]
#   title = "Android Gradleæƒå¨æŒ‡å—"
#   name = "Android Gradleæƒå¨æŒ‡å—"
#   url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"

## ä¾§è¾¹æ å¹¿å‘Šä½
[[params.ads]]
  title = "æˆ‘åœ¨ä½¿ç”¨ä¸é™é€Ÿã€Œé˜¿é‡Œäº‘ç›˜ã€ï¼Œèµ é€ä½  500GB å¿«æ¥è¯•è¯•å§ ğŸ‰"
  url = "https://pages.aliyundrive.com/mobile-page/web/beinvited.html?code=0d9686e"
  img = "/aliyundrive.png"
# [[params.ads]]
#   title = "åŠ©åŠ›äº§ä¸šæ™ºæ…§å‡çº§ï¼Œäº‘æœåŠ¡å™¨é¦–å¹´88å…ƒèµ·ï¼Œæ›´æœ‰åƒå…ƒä»£é‡‘åˆ¸ç¤¼åŒ…å…è´¹é¢†ï¼"
#   url = "https://cloud.tencent.com/act/cps/redirect?redirect=1048&cps_key=14ff722692ac784fa8c3301c8c28d924&from=console"
#   img = "https://upload-dianshi-1255598498.file.myqcloud.com/345-7c71532bd4935fbdd9a67c1a71e577b1767b805c.200%E7%89%88%E6%9C%ACB.jpg"
# [[params.ads]]
#   title = "ã€æ¸ é“ä¸“äº«ä½æŠ˜æ‰£ã€‘11æœˆç‰¹æƒ  é™æ—¶2æŠ˜"
#   url = "https://www.aliyun.com/acts/limit-buy?userCode=jdg9oj97"
#   img = "https://img.alicdn.com/tfs/TB1hblJl7Y2gK0jSZFgXXc5OFXa-750-400.jpg"

## é…ç½® utterancè¯„è®º,æ•™ç¨‹å‚è€ƒ https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "MaoLongLong/maolonglong.github.io" ##æ¢æˆè‡ªå·±å¾—
  issueTerm = "pathname"
  theme = "github-light"

## å¼€å¯ç‰ˆæƒå£°æ˜ï¼Œåè®®åå­—å’Œé“¾æ¥éƒ½å¯ä»¥æ¢
# [params.cc]
#     name = "çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç¦æ­¢æ¼”ç» 4.0 å›½é™…è®¸å¯åè®®"
#     link = "https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh"

## é…ç½®ä»£ç é«˜äº®
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## é…ç½®ç½‘ç«™èœå•

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "å½’æ¡£"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "å…³äº"
    url = "/about/"
    weight = 3
